name: Python Code Quality
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'
    - name: Install dependencies
      run: |
        pip install black pylint
    - name: Run Black
      run: black --check .
    - name: Run Pylint
      run: pylint $(git ls-files '*.py')
